version: "3.2"
services:
    redis:
        image: redis:5.0.0-alpine
        restart: always
        container_name: myapp-redis
        ports:
            - 6379:6379
        networks:
             myapp_net:

    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
        restart: always
        container_name: myapp-es
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
        networks:
            myapp_net:

    db:
        image: mysql:5.7.24
        restart: always
        container_name: myapp-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: mydb
        ports:
            - "3306:3306"
        volumes:
            - /data/mysql:/var/lib/mysql
        networks:
            myapp_net:

    app:
        build: .
        restart: always
        container_name: myapp-web
        depends_on:
            - db
            - redis
            - es
        ports:
            - "8888:80"
        volumes:
            - .:/var/www/myapp
        networks:
            myapp_net:

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
          - db
        depends_on:
          - db
        ports:
          - '8080:80'
        networks:
            myapp_net:

volumes:
    web-app:
        driver: local
networks:
    myapp_net:
        driver: bridge
        ipam:
            driver: default
